# Generated by Django 3.2 on 2021-05-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('image', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
